### ISSUE TITLE
Broken code in the gallery / notebook execution flags not working

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythia/xbatcher-ML-1-cookbook#11]
Currently we're publishing some broken code on our gallery, see here:
https://projectpythia.org/xbatcher-ML-1-cookbook/notebooks/surface_currents.html#data-and-preprocessing

This is a data access problem that's already been discussed in https://github.com/ProjectPythia/xbatcher-ML-1-cookbook/pull/4 and https://github.com/ProjectPythia/xbatcher-ML-1-cookbook/issues/5.

It seems like the workaround was to suppress notebook execution during the build. Currently we have in the `_config.yml`:
```
execute:
  # To execute notebooks via a binder instead, replace 'cache' with 'binder'
  execute_notebooks: force
  exclude_patterns:
    - "notebooks/surface_currents_prep.ipynb"
    - "notebooks/surface_currents_model.ipynb"
```

But those notebooks are executing anyway during the build. I'm not sure why those flags aren't working.

This repo is also missing the flag `nb_execution_raise_on_error: true` which would normally prevent our build system from publishing to GitHub Pages if there's a notebook error. PR https://github.com/ProjectPythia/xbatcher-ML-1-cookbook/pull/8 puts that flag in, but is currently failing the build (because the problematic notebook is still executing).
